# Generated by Django 3.0.3 on 2020-03-02 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctions_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='id_category',
            field=models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.PROTECT, to='auctions.Category'),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='id_auction',
            field=models.ForeignKey(db_column='id_auction', on_delete=django.db.models.deletion.PROTECT, to='auctions.Auctions'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='id_auction',
            field=models.ForeignKey(db_column='id_auction', on_delete=django.db.models.deletion.CASCADE, to='auctions.Auctions'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
