# Generated by Django 3.0.3 on 2020-03-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('id_auction', 'id_user')},
        ),
    ]
