# Generated by Django 3.0.3 on 2020-03-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200303_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='Amount',
            new_name='amount',
        ),
    ]
