# Generated by Django 3.0.3 on 2020-03-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200305_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
